language: python

sudo: required
dist: trusty

python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 2.7

after_success:
  - codecov
  - coveralls

cache:
  pip: true
  directories:
    - .tox

env:
  matrix:
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'
  - TESTS='run'

install:
  - travis_retry pip install -r requirements-test.txt
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ ${TESTS}z != 'z' ]]; then export TOXENV=$PYVER; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$TOXENV

matrix:
  exclude:
  - python: 2.7
    env: TOXENV='pep8'
  - python: 2.7
    env: TOXENV='isort'
  - python: 2.7
    env: TOXENV='docs'
  - python: 3.4
    env: TOXENV='pep8'
  - python: 3.4
    env: TOXENV='isort'
  - python: 3.4
    env: TOXENV='docs'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='docs'

jobs:
  include:
    - stage: package
      env:
        PACKAGE=1
      install:
        - sudo apt-get install -yq --no-install-suggests --no-install-recommends
          devscripts fakeroot equivs
        - mk-build-deps -i -s sudo -t 'apt-get -yq' debian/control
        - echo 'APT::Default-Release "trusty";' | sudo tee /etc/apt/apt.conf
        - echo 'deb http://archive.ubuntu.com/ubuntu xenial main' |
          sudo tee /etc/apt/sources.list.d/xenial.list
        - sudo apt-get update
        - sudo apt-get install -yq --no-install-suggests --no-install-recommends
          -t xenial
          python-dateutil python-requests python-six
          python3-dateutil python3-requests python3-six
      script: make deb
      before_script: skip
      after_success: skip
